name: Deploy to S3

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Sync files to S3
      run: |
        aws s3 sync ./ s3://maryboroughmowerman --delete --exact-timestamps --exclude ".github/*"
        
    - name: Apply S3 website configuration
      run: |
        aws s3api put-bucket-website --bucket maryboroughmowerman --website-configuration file://aws-website-config.json
        
    - name: Invalidate CloudFront
      run: |
        aws cloudfront create-invalidation --distribution-id E2H5EBMSGI9L7N --paths "/*"